config/routes.rb
Smokit::Application.routes.draw do
  get "home/index"
  post "/newsmoke", to: "smokes#create2"
  resources :smokes
 
  get "/users/name/:name", to: "users#display"
  resources :users

resources :sessions, only: [:new, :create, :destroy]
get '/signin', to: 'sessions#new'
delete '/signout', to: 'sessions#destroy'

  root :to => "home#index"

  

end

app/models/smoke.rb
class Smoke < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_uniqueness_of :name
	has_many :smokes
	validates :name, length: {maximum: 16, minimum: 0}

  before_create :create_remember_token
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 	include SessionsHelper
 after_filter :add_flash_to_header

  def add_flash_to_header
    # only run this in case it's an Ajax request.
    return unless request.xhr?

    # add different flashes to header
    response.headers['X-Flash-Error'] = flash[:error] unless flash[:error].blank?
    response.headers['X-Flash-Warning'] = flash[:warning] unless flash[:warning].blank?
    response.headers['X-Flash-Notice'] = flash[:notice] unless flash[:notice].blank?
    response.headers['X-Flash-Message'] = flash[:message] unless flash[:message].blank?

    # make sure flash does not appear on the next page
    flash.discard
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
	user= User.find_by(name: params[:session][:name])
	if User.exists?(user)	
	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
	cookies.permanent[:username] = user.name
    	user.update_attribute(:remember_token, User.encrypt(remember_token))
    	##self.current_user = user
	redirect_to "/" 
	puts "=========== "
	else
	#Grosse tricherie ici pour faire bugger rails pour que la reponse ajax ait des headers d'erreur et fasse bien apparaitre l'erreur comme on le souhaite !
	#La ligne suivante bug donc, sans que je sache pourquoi héhé
	render status: :unprocessable_entity
	end
end

  #def current_user=(user)
   # @current_user = user
  #end
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

end

app/controllers/smokes_controller.rb
class SmokesController < ApplicationController
  before_action :set_smoke, only: [:show, :edit, :update, :destroy]

  # GET /smokes
  # GET /smokes.json
  def index
    @smokes = Smoke.all
  end

  # GET /smokes/1
  # GET /smokes/1.json
  def show
	@smoke = Smoke.find(params[:id])
  end

  # GET /smokes/new
  def new
    @smoke = Smoke.new
  end

  # GET /smokes/1/edit
  def edit
  end

  # POST /smokes
  # POST /smokes.json
  def create
    @smoke = Smoke.new(smoke_params)
	
    respond_to do |format|
      if @smoke.save
        format.html { redirect_to @smoke, notice: 'Smoke was successfully created.' }
        format.json { render action: 'show', status: :created, location: @smoke }
      else
        format.html { render action: 'new' }
        format.json { render json: @smoke.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST zdzd/smokes
  # POST zdz/smokes.json

def create2
@userP = params[:user]
@smokeP = params[:smoke]
 
@user = User.find_by_name [@userP[:name]]
@smoke = Smoke.new(user_id: @user.id, smoke_date: @smokeP[:smoke_date], smoke_latitude: @smokeP[:smoke_latitude], smoke_longitude: @smokeP[:smoke_longitude])
    respond_to do |format|
      if @smoke.save
        format.html { redirect_to @smoke, notice: 'Smoke was successfully created.' }
        format.json { render action: 'show', status: :created, location: @smoke }
      else
        format.html { render action: 'new' }
        format.json { render json: @smoke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smokes/1
  # PATCH/PUT /smokes/1.json
  def update
    respond_to do |format|
      if @smoke.update(smoke_params)
        format.html { redirect_to @smoke, notice: 'Smoke was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @smoke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smokes/1
  # DELETE /smokes/1.json
  def destroy
    @smoke.destroy
    respond_to do |format|
      format.html { redirect_to smokes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smoke
      @smoke = Smoke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smoke_params
      params.require(:smoke).permit(:user_name, :user_id, :smoke_date, :smoke_latitude, :smoke_longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end
  
  #GET /users/name
  def display
 	@user = User.find_by_name params[:name] 
	respond_to do |format|
	 format.html
	 #display.html.erb #format.json { render json: @user.smokes }
	@name = @user.name 
	@smokes = @user.smokes 
	format.json { render :json => {:name => @name , :smokes => @smokes}}
	end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
#Cette ligne permet de renvoyer une erreur à jquery si l'utilisateur existe déja
      if (!User.exists?(@user) && @user.save)
	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
	cookies.permanent[:username] = @user.name
    	@user.update_attribute(:remember_token, User.encrypt(remember_token))
	#puts "=============================================="
        format.html {redirect_to "/", notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
	#puts " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "
        format.html { redirect_to "/"}
	#render 'new'
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/smokes_helper.rb
module SmokesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smokit</title>
  </head>

  <body>

<!--Partie de code qui sera utilisée en non connecté-->
<div class='disconnected'>
<p id="error1" style="display:none; color:red">Username non existant!</p>	
<p id="error2" type="hidden" style="display:none; color:red">Username déja pris!</p>
	<h1>Smokit, la partie Web</h1>
	<h2 id="title">Username :</h2>
		<input id="username_connect" type="text">
		<input id="connect" type="submit" value="Connection">
	<br/><br/>

	<p> Pas encore Inscrit ? </p>
	<h2>Nouveau Username :</h2>

		<input id="username_create" type="text">
		<input id="create" type="submit" value="Soumettre">
	<p> 
		<a href="/users">Manage Users</a><br/>
		<a href="/smokes">Manage Smokes</a>
	</p>
</div>

<!--Partie de code qui sera utilisée en connecté-->
<div class='connected'>
	<h2 id="title_smoke"></h2>
<!--Beaucoup d'animations Jquery à faire la-->
	<input id="smoke" type="submit" value="New Smoke">
	<br/>
	<input id="go_smoke_stats" type="submit" value="Voir l'évolution de ton cancer !">
</div>

<!--Partie de code qui sera utilisé en stats-->
<div class='stats'>
	<h2 id="title_stats"></h2>
	<table id="stat_table">
		<tr id="title_tr">
			<th>Date</th>
			<th>Latitude</th>
			<th>Longitude</th>
		</tr>
	</table>
<input id="go_stats_smoke" type="submit" value="Encore se rapprocher du cancer ?">
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smokit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/smokes/_form.html.erb
<%= form_for(@smoke) do |f| %>
  <% if @smoke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@smoke.errors.count, "error") %> prohibited this smoke from being saved:</h2>

      <ul>
      <% @smoke.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :smoke_date %><br>
    <%= f.datetime_select :smoke_date %>
  </div>
  <div class="field">
    <%= f.label :smoke_latitude %><br>
    <%= f.text_field :smoke_latitude %>
  </div>
  <div class="field">
    <%= f.label :smoke_longitude %><br>
    <%= f.text_field :smoke_longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/smokes/_smoke.html.erb
	<tr>
		<td><%= smoke.smoke_date %></td>
		<td><%= smoke.smoke_latitude %></td>
		<td><%= smoke.smoke_longitude %></td>
	</tr>
		
	

app/views/smokes/edit.html.erb
<h1>Editing smoke</h1>

<%= render 'form' %>

<%= link_to 'Show', @smoke %> |
<%= link_to 'Back', smokes_path %>

app/views/smokes/index.html.erb
<h1>Listing smokes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Smoke date</th>
      <th>Smoke latitude</th>
      <th>Smoke longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @smokes.each do |smoke| %>
      <tr>
        <td><%= smoke.user_id %></td>
        <td><%= smoke.smoke_date %></td>
        <td><%= smoke.smoke_latitude %></td>
        <td><%= smoke.smoke_longitude %></td>
        <td><%= link_to 'Show', smoke %></td>
        <td><%= link_to 'Edit', edit_smoke_path(smoke) %></td>
        <td><%= link_to 'Destroy', smoke, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Smoke', new_smoke_path %>
<a href="/">Back</a>

app/views/smokes/new.html.erb
<h1>New smoke</h1>

<%= render 'form' %>

<%= link_to 'Back', smokes_path %>

app/views/smokes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @smoke.user_id %>
</p>

<p>
  <strong>Smoke date:</strong>
  <%= @smoke.smoke_date %>
</p>

<p>
  <strong>Smoke latitude:</strong>
  <%= @smoke.smoke_latitude %>
</p>

<p>
  <strong>Smoke longitude:</strong>
  <%= @smoke.smoke_longitude %>
</p>

<%= link_to 'Edit', edit_smoke_path(@smoke) %> |
<%= link_to 'Back', smokes_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_users.html.erb
<p>
	<b>User:</b>
	<%= users.body %>
</p>

app/views/users/display.html.erb
		<%= render @user.smokes %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<a href="/">Back</a>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>Name:
  <%= @user.name %></h1>
</p>
	

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>